server:
  port: 8081
spring:
  application:
    name: halo-docs

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/


## 解决zuul不能传递cookie的问题
zuul.sensitive-headers:
